### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by DevulderJeanPaul** [PasiSalenius/CocoaCompose#2]
Hi,

let radio = Radio(items: [
    Radio.Item(title: "First"),
    Radio.Item(title: "Second", views: [
        TextField(value: "30", trailingText: "seconds") { text in
            // do something here ...
        },
    ])
    
], selectedIndex: 0) { index in
    // do something here ...
}

// *****error { index in    need two parameters

**Comment by PasiSalenius** [comment]
Thanks for letting me know!
